import { Dimensions, StyleSheet } from "react-native";
import color from '../../styles/color';
const btn_text_font_size = Dimensions.get("window").width/20

const base_style = StyleSheet.create({
    container:{
        width:Dimensions.get("window").width/1.2,
        //height:Dimensions.get("window").height/20,
        borderRadius:20,
        borderWidth:1,
        justifyContent:"center",
        alignItems:"center",
        padding:"3%"
    },
    text:{
        fontSize:btn_text_font_size,
        fontWeight:"bold"
    }
})

export default{
    primary:StyleSheet.create({
        ...base_style,
        container:{
            ...base_style.container,
            backgroundColor:color.brown,
            borderColor:color.brown,
        },
        text:{
            ...base_style.text,
            color:color.white,
        }
    }),
    secondary:StyleSheet.create({
        ...base_style,
        container:{
            ...base_style.container,
            backgroundColor:color.white,
            borderColor:color.brown,
        },
        text:{
            ...base_style.text,
            color:color.brown,
        }
    }),
    third:StyleSheet.create({
        ...base_style,
        container:{
            ...base_style.container,
            backgroundColor:color.green,
            borderColor:color.green,
        },
        text:{
            ...base_style.text,
            color:color.white,
        }
    }),
    fourth:StyleSheet.create({
        ...base_style,
        container:{
            ...base_style.container,
            backgroundColor:color.blue,
            borderColor:color.blue,
        },
        text:{
            ...base_style.text,
            color:color.white,
        }
    }),
    fifth:StyleSheet.create({
        ...base_style,
        container:{
            ...base_style.container,
            backgroundColor:color.orange,
            borderColor:color.orange,
        },
        text:{
            ...base_style.text,
            color:color.white,
        }
    })
}